version: '3'

services:
  backend:
    build: ./backend                   # katalog z Dockerfile, package.json, server.js, .env
    container_name: designweb-backend
    env_file:
      - ./backend/.env
    dns:
      - 192.168.226.1
    expose:
      - "3000"                         # udostępnia port tylko wewnątrz tej sieci dockera
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: designweb-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro               # pliki frontend
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro # twój config nginx.conf
      - ./certs:/etc/nginx/certs:ro                   # certyfikaty SSL
    depends_on:
      - backend
    restart: unless-stopped
