version: "3.8"

services:
  backend:                       # usługa z Node
    build: ./backend
    container_name: my-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/app

  frontend:                      # Nginx do frontendu
    image: nginx:alpine
    container_name: my-frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
